
version: '3.9'

services:
  iroa-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - iroa-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: iroa_db
      POSTGRES_USER: iroa_user
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - iroa-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - iroa-net

networks:
  iroa-net:

volumes:
  pgdata:
